name: json_to_model
description: Generate model class from Json file.
version: 3.2.4+2
homepage: https://github.com/fadhilx/json_to_model

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  args: ^2.3.1
  logging: ^1.1.0
  path: ^1.8.3
  yaml: ^3.1.1

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.1
